name: Run carga Tests (k6)

on:
  push:
    branches: [ main, master, develop ]
  pull_request:

jobs:
  k6-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout k6-reporter
        uses: actions/checkout@v4
        with:
          repository: grafana/k6-reporter
          path: k6-reporter

      - name: Build k6-reporter
        run: |
          cd k6-reporter
          npm install
          npm run build

      - name: Run k6 and generate json
        run: |
          k6 run --out json=resultado.json teste_carga.js

      - name: Generate HTML Report
        run: |
          node k6-reporter/dist/cli.js ../resultado.json

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: k6-html-report
          path: summary.html